// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmtZZ4I7nZGKzmXs3YzAjF8KdY7xbOpMQ',
    appId: '1:349858250623:web:7ab2d06367a9382378e44a',
    messagingSenderId: '349858250623',
    projectId: 'insplanet-app',
    authDomain: 'insplanet-app.firebaseapp.com',
    storageBucket: 'insplanet-app.firebasestorage.app',
    measurementId: 'G-TP45YEYEBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjZ8h9VtfL7IcUIM6LL0U924NU-eoIiz0',
    appId: '1:349858250623:android:31aca4501ea7a69178e44a',
    messagingSenderId: '349858250623',
    projectId: 'insplanet-app',
    storageBucket: 'insplanet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgeoJCqq9kDWbaexkyK58XOc5CZwIatMU',
    appId: '1:349858250623:ios:c576fd193c52cde278e44a',
    messagingSenderId: '349858250623',
    projectId: 'insplanet-app',
    storageBucket: 'insplanet-app.firebasestorage.app',
    iosClientId:
        '349858250623-ta57ucb92u6nklarvua4c9ho89rqrb3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgeoJCqq9kDWbaexkyK58XOc5CZwIatMU',
    appId: '1:349858250623:ios:c576fd193c52cde278e44a',
    messagingSenderId: '349858250623',
    projectId: 'insplanet-app',
    storageBucket: 'insplanet-app.firebasestorage.app',
    iosClientId:
        '349858250623-ta57ucb92u6nklarvua4c9ho89rqrb3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmtZZ4I7nZGKzmXs3YzAjF8KdY7xbOpMQ',
    appId: '1:349858250623:web:4c66e475e897255878e44a',
    messagingSenderId: '349858250623',
    projectId: 'insplanet-app',
    authDomain: 'insplanet-app.firebaseapp.com',
    storageBucket: 'insplanet-app.firebasestorage.app',
    measurementId: 'G-W0ZJQKKBG6',
  );
}
